### ISSUE TITLE
formani ichida button type=submit

### ISSUE THREAD

**Issue by Abdulaziz6665** [malikabakhtiyorova/ToDoList#2]
![изображение](https://user-images.githubusercontent.com/68459496/98700880-7df3d680-239a-11eb-8f8b-54dcd689ec78.png)
input ga qiymat yozib enter bosilganda listga qo'shmadi.  button ni type=submit bo'sa  ishlashi mumkun.

**Comment by malikabakhtiyorova** [comment]
Rahmat, to'g'irlab qo'ydim.
